name: cikm20-causenet
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - maven=3.6.0=0
  - python=3.7.3
  - notebook=5.7.8
  - pandas=0.24.2
  - pip=20.1.1
  - numpy=1.18.4
  - nltk=3.4.1
  - neo4j-python-driver=1.7.2
  - tabulate==0.8.3
  - requests=2.22.0
  - tldextract=2.2.0
  - sparqlwrapper=1.8.2
  - pytorch=1.2.0
  - spacy=2.1.8
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm
    - flair==0.4.2
    - stanfordnlp==0.2.0
